completed css-three-column-layout exercise, avallon smith
avallonsmith/rc0122-code-solutions pull request #19
Opened 2022-01-28 02:40 UTC by avallonsmith

![image](https://user-images.githubusercontent.com/96964291/151477879-6edbb95d-c086-4ab7-a194-6d9780a13027.png)

2022-01-28 05:37 UTC, Zhiwutian requested changes
Make sure to remove the padding for layout, and let me know if you have questions on another approach!

2022-01-28 05:37 UTC, Zhiwutian commented on css-three-column-layout/styles.css
> +  padding-left: 250px;
you don't want to use padding for layout. make sure to avoid doing that. There is always a better way!

2022-02-02 03:50 UTC, avallonsmith commented
![image](https://user-images.githubusercontent.com/96964291/152090284-97e18e4d-4f8f-4bf6-92da-3972029fa11c.png)
no more padding B)

2022-02-02 04:29 UTC, Zhiwutian requested changes
make sure to delete the commented code!

2022-02-02 18:02 UTC, avallonsmith commented
Should be good now!

2022-02-03 17:43 UTC, Zhiwutian approved these changes
👍🏼

2022-02-03 18:02 UTC, merged