css two column layout, avallon smith
avallonsmith/rc0122-code-solutions pull request #21
Opened 2022-01-29 02:34 UTC by avallonsmith

![image](https://user-images.githubusercontent.com/96964291/151643953-6f20b6a2-7002-4b1e-9c35-b2faa9178291.png)

2022-01-29 15:05 UTC, Zhiwutian requested changes
small HTML update, looking good!

2022-01-29 15:05 UTC, Zhiwutian commented on css-two-column-layout/index.html
> +      <div class="column-one-sixth">
only thing I would recommend for the HTML is to wrap the `column-one-sixth` and `column-two-sixths` elements with a `column-one-half` as the parent so you have two total columns per row:
```html
<div class="column-half">
   <div class="column-one-sixth">
    <img src="images/circumstance.svg" alt="Circumstance">
  </div>
  <div class="column-two-sixths space">
    <h3>FOR ANY CIRCUMSTANCE</h3>
    <p>Our intuitive system is built around the
    peculiarities of your facility; we support
    offline deployments, sync to the cloud
    and run on any device 24/7.</p>
  </div>
</div>
```

Keep up the good work!

2022-02-02 06:38 UTC, avallonsmith commented
![image](https://user-images.githubusercontent.com/96964291/152105872-5d549dec-4c4d-4b54-bd4f-a8664294d852.png)

2022-02-03 17:44 UTC, Zhiwutian approved these changes
👍🏼

2022-02-03 18:02 UTC, merged